<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>sentor</name>
  <version>2.2.0</version>
  <description>The sentor package, to monitor ROS messages</description>

  <maintainer email="fdelduchetto@lincoln.ac.uk">Francesco Del Duchetto</maintainer>
  <maintainer email="abinch@sagarobotics.com">Adam Binch</maintainer>
  <maintainer email="marc@hanheide.net">Marc Hanheide</maintainer>

  <license>MIT</license>

  <author email="fdelduchetto@lincoln.ac.uk">Francesco Del Duchetto</author>
  <author email="abinch@sagarobotics.com">Adam Binch</author>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>tf2_ros</depend>
  <depend>tf2</depend>
  <depend>rcl_interfaces</depend>
  <depend>rosidl_default_generators</depend>

  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>

  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>